#!/bin/zsh

fg_color=colour230
bg_color=colour245
space_bg_color=colour240

mydate() {
    date '+%Y/%m/%d %a %H:%M'
}

myuptime() {
    uptime|grep -o 'up [^,]*'
}

mybattery() {
    echo -n 'battery: '
    upower -i /org/freedesktop/UPower/devices/battery_BAT0 | \
        grep percentage | egrep -o '[0-9]*%'
    upower -i /org/freedesktop/UPower/devices/battery_BAT0 | \
        grep 'time to empty' | sed 's/^ *time to empty: *//'
}

display_commands=(mybattery myuptime mydate)

for com in $display_commands; do
    echo -n "#[fg=${fg_color},bg=${bg_color},bold]["
    echo -n `${com}`
    echo -n "]#[bg=${space_bg_color}] "
done
